"""empty message

Revision ID: 166e37d1573c
Revises: 
Create Date: 2023-11-20 12:19:24.565230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166e37d1573c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('dns', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('peer_config', sa.String(length=50), nullable=True))
        batch_op.drop_column('config')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('peer_config')
        batch_op.drop_column('dns')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
