# Web Server Configuration
TEMPLATES_AUTO_RELOAD: True
SQLALCHEMY_TRACK_MODIFICATIONS: True
SQLALCHEMY_DATABASE_URI: 'sqlite:///{basedir}/wg.db'
HOST_IP: '127.0.0.1'
HOST_PORT: '5000'
BASE_DIR: '{basedir}'

# MODE can be database or server
MODE: 'database'

# User Session Management
SECRET_KEY: 'changemechangemechangemechangeme'
SUDO_PASSWORD: 'password'

# TLS configuration
PKI_CERT_PATH: '{basedir}/pki'
PKI_CERT: 'cert.pem'
PKI_KEY:  'key.pem'

# Network Configuration
BASE_IP: '10.100.200.0'
BASE_IP6: 'fd00:100:200::'
BASE_NETMASK: '24'
BASE_NETMASK6: '64'
BASE_PORT: '51820'
BASE_PORT6: '51820'
BASE_DNS: ''
BASE_DNS6: ''
BASE_KEEPALIVE: '25'
ADAPTER_PREFIX: 'wg'
PEER_ACTIVITY_TIMEOUT: 300

# Data Files
OUTPUT_DIR: '{basedir}/output'

# Logging
LOG_DIR: '{basedir}/logs'
